"""
Django settings for Django_Project project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# 获取当前项目的绝对路径
# 用于绑定当前项目前绝对路径（动态计算出来前），所有文件夹都可以依赖此路径
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# setting中的加密盐，该配置是django的安全限置，防止攻击用的，该值是startProject时用系统的某个来个算法产生的.
SECRET_KEY = 'django-insecure-95=t=*8ha0*p3v3t$+fjmv0n*5$vl3bx4pcr9qanjfqa9x8wt4'

# SECURITY WARNING: don't run with debug turned on in production!
# 调试模式，一般默认 true
DEBUG = True

# 请求头 Host 头校验配置
# 用于配置当前 Django 站点允许被哪些域名或 IP 地址访问（校验请求头中的 Host 字段），
# 主要用于防范 HTTP Host 头攻击。
# 当 DEBUG = False 时，此项为必填项，有以下几种使用方法：
# []，空列表。在 DEBUG = False 时，表示拒绝所有请求（包括 127.0.0.1 和 localhost）；
#     在 DEBUG = True 时，默认放行 127.0.0.1、localhost 和 [::1]。
# ['*']，通配符。表示不校验 Host 头，允许通过任何域名或 IP 访问当前项目（生产环境极不安全，不推荐）。
# ['192.168.1.3', '192.168.3.3']，表示只允许通过这两个 IP 地址（或域名）来访问当前项目。
#     例如：客户端访问 http://192.168.1.3:8000/ 会成功，但访问 http://其他IP:8000/ 会被返回 400 Bad Request。
# 注意：它限制的是“服务端可以被哪些域名/IP访问”，而不是“限制哪些客户端IP可以来访问”。
ALLOWED_HOSTS = []


# Application definition

# app 应用的安装配置⭐️
# 添加注册 app，每添加一个 app 都需要在该apps配置下添加一个
INSTALLED_APPS = [
    'django.contrib.admin',# 管理站点，即 admin 后台功能
    'django.contrib.auth',# admin 后台权限认证管理
    'django.contrib.contenttypes',# 用于内容类型的框架
    'django.contrib.sessions',# 会话管理
    'django.contrib.messages',# 消息管理
    'django.contrib.staticfiles',# 静态文件管理
    # 添加注册的 app
    'indexApp.apps.IndexappConfig',
    'kuma.apps.KumaConfig',
]

# 中间件配置⭐️
# django 的中间件配置，即 MIDDLEWARE 设置，
# 所谓中间件就是从用户请求到用户请求结束期间所做的操作，
# 即用户的请求会次从上到下依次执行 MIDDLEWARE 中的配置，
# 然后服务器响应用户的时候会再次从下至上依次执行，
# 在 request 请求前后，和 response 响应前后执行
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # 安全中间件
    'django.contrib.sessions.middleware.SessionMiddleware',  # 会话中间件，启用会话框架
    'django.middleware.common.CommonMiddleware',  # 通用中间件
    # CSRF防御中间件,增加防御保护以防止跨站伪造请求攻击。
    # 通过向表单Post请求中添加隐藏表单字段以及对请求进行检查以获取正确的值。
    'django.middleware.csrf.CsrfViewMiddleware',
    # admin用户认证中间件,在每个HttpRequest请求对象中添加user属性，表名当前已登录的用户
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # 消息中间件，提供Django的cookie以及session框架的支持，这两个基于消息中间件实现。
    'django.contrib.messages.middleware.MessageMiddleware',
    # X框架操作中间件，通过头部信息中增加X-Frame-OptionsLAI 防止简单的点击劫持。
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# 指定根级url钓配置
# django 路由文件位置 - 一般不会改变
ROOT_URLCONF = 'Django_Project.urls'

# 模板相关配置
# 它用于指定模板的配置信息，列表中每一元素都是一个字典。如下所示是 Django 默认自带模板引擎
# 全局上下文处理器提供的变量优先级高于单个视图函数给单个模板传递的变量。
# 这意味着全局上下文处理器提供的变量可能会覆盖你视图函数中自定义的本地变量，
# 因此请注意避免本地变量名与全局上下文处理器提供的变量名称重复。
# 这些变量名包括perms，user和debug等等。
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# 正式启动会用
# 项目部署时，Django的内置服务器将使用的WSGI应用程序对象的完整Python路径。
WSGI_APPLICATION = 'Django_Project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Database⭐️
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases
# 设置数据源
# 数据库连接配置，也可以以配置文件的形式加载数据库信息
# django目前支持sqlite、mysql、postgreSQL、oracle数据库
# sqlite数据库: 'django.db.backends.sqlite3',
# postgreSQL数据库: 'django.db.backends.postgresql_psycopg2',
# mysql数据库: 'django.db.backends.mysql'
# oracle数据库: 'django.db.backends.oracle'
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators
# 这是一个支持插拔的密码验证器，且可以一次性配置多个，
# Django 通过这些内置组件来避免用户设置的密码等级不足的问题。
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/
# 语言信息配置
# 'zh-Hans'  改成中文
# 设置语言zh-hans，zh-cn，en-us
LANGUAGE_CODE = 'zh-hans'

# 时区，默认是格林威治时间
# 'Asia/Shanghai' 修改成亚洲时间
# 设置时区Asia/Shanghai，UTC
TIME_ZONE = 'UTC'

# 设置国际化，根据个人需要进行设置：
USE_I18N = True

# 设置保存到数据库时间类型是否为UTC时间，如果不需要请设置为false,默认为true
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

# Static files (CSS, JavaScript, Images)-必须手动添加这三个才能使用功能⭐️
# https://docs.djangoproject.com/en/3.2/howto/static-files/
# 它指的是静态资源的存放位置，静态资源包括 CSS、JS、Images。比如我们要在项目中添加一些图片，
# 通常这些静态图片被存放在新建的 static 目录下，这样就实现了通过 STATIC_URL= '/static/' 路径对静态资源的访问。
STATIC_URL = 'static/'

# 静态文件的路径
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]

# 设置文件上传存储路径
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
# 文件的统一路由
MEDIA_URL = "/media/"

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field
# models.py中的class实体类，没有手动添加id主键属性，使用django自动生成
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
